# generated by mBlock5 for CyberPi
# codes make you happy

import cyberpi, time, event, mbot2
# initialize variables
import socket
cyberpi.network.config_sta('iotpractica', '')
cyberpi.network.create_client()
HEADER = 64
PORT = 5050
FORMAT ='utf-8'
DISCONNECT_MESSAGE = '!DISCONNECT'
SERVER = '192.168.0.101'
ADDR = (SERVER,PORT)
client = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
client.connect(ADDR)

def move(moved):
    if moved == 'up':
        mbot2.EM_set_speed(50, "ALL")
        time.sleep(1)
        mbot2.EM_stop("ALL")
    if moved == 'left':
        mbot2.EM_set_speed(50, "EM1")
        time.sleep(1)
        mbot2.EM_stop("EM1")

def send(msg):
    message = msg.encode(FORMAT)
    msg_lenght = len(message)
    send_lenght=str(msg_lenght).encode(FORMAT)
    send_lenght += b' '*(HEADER-len(send_lenght))
    client.send(send_lenght)
    client.send(message)
    recv = client.recv(2048).decode(FORMAT)
    cyberpi.console.print(recv+'\n')
    move(str(recv))


@event.start

def on_start():
    cyberpi.network.config_sta('iotpractica', '')
    cyberpi.network.create_client()
    while not cyberpi.network.is_connect():
        pass

    cyberpi.led.show('green green green green green')
    cyberpi.console.print(cyberpi.network.get_ip())
    cyberpi.led.show('cyan cyan cyan cyan cyan')
 

@event.is_press('b')
def is_btn_press():
    send('127 holaaa')

@event.is_press('a')
def is_btn_press():
    send('cosasssss')

@event.is_press('middle')
def is_joy_press():
    cyberpi.console.clear()